
import { jsPDF } from "jspdf";
import { Note } from "./storage";

export const createPDF = async (text: string, title: string = "Note") => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - (margin * 2);

  // Branding Header
  doc.setFillColor(37, 99, 235); // Blue-600
  doc.rect(0, 0, pageWidth, 2, 'F');
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(30, 41, 59);
  doc.text(title.toUpperCase(), margin, 25);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated by AP_NOTES - ${new Date().toLocaleString()}`, margin, 32);

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, 38, pageWidth - margin, 38);

  // Content
  doc.setFontSize(11);
  doc.setTextColor(51, 65, 85);
  const splitText = doc.splitTextToSize(text, contentWidth);
  
  let cursorY = 48;
  const lineHeight = 7;

  splitText.forEach((line: string) => {
    if (cursorY > pageHeight - 20) {
      doc.addPage();
      cursorY = 20;
    }
    doc.text(line, margin, cursorY);
    cursorY += lineHeight;
  });

  // Footer/Dragon Logo placeholder (could be text)
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  doc.save(`${title.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`);
};

export const exportAllNotesToPDF = (notes: Note[]) => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - (margin * 2);
  const lineHeight = 7;

  notes.forEach((note, index) => {
    if (index > 0) {
      doc.addPage();
    }
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text(note.title, margin, 20);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`Created: ${new Date(note.createdAt).toLocaleString()}`, margin, 28);
    
    doc.line(margin, 32, pageWidth - margin, 32);
    
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(note.text, contentWidth);
    
    let cursorY = 40;
    splitText.forEach((line: string) => {
      if (cursorY > pageHeight - 20) {
        doc.addPage();
        cursorY = 20;
      }
      doc.text(line, margin, cursorY);
      cursorY += lineHeight;
    });
  });

  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Archive - Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  doc.save(`Complete_Archive_${new Date().getTime()}.pdf`);
};
